@beginURL = http://localhost:5200


### alle brouwers
GET {{beginURL}}/brouwers

### brouwer 1:
GET {{beginURL}}/brouwers/2

### een onbestaande brouwer:
GET {{beginURL}}/brouwers/666666666

### brouwer 3 verwijderen:
DELETE {{beginURL}}/brouwers/3

### een brouwer toevoegen:
POST {{beginURL}}/brouwers
content-type: application/json

{
  "naam" : "Test",
  "postcode":10,
  "gemeente":"Ertvelde"
}

### brouwer 2 wijzigen:
PUT {{beginURL}}/brouwers/2
Content-Type:application/json

{
  "naam":"Alken",
  "postcode":1000,
  "gemeente":"Brussel"
}